server:
  port: 8056
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.chloneda.domain
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

